image:
  repository: registry.gitlab.com/kubeaiops/platform/capacity-api
  tag: v0.2.0
  pullPolicy: IfNotPresent

demoWorkload:
  enabled: false

monitoring:
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true
